// The contract between the hangar core and a plugin.
//
// Everything a person can ask for is a plugin. A plugin DECLARES what it
// offers (Describe) and ACTS when the core asks it to (Configure, Plan,
// Create, Delete, Act, Reconcile). It never calls the core, it never sees
// another plugin's credential, and it never decides who may ask: identity,
// tiers, limits, the registry and the audit belong to the core.
//
// Values that are JSON documents travel as bytes holding JSON (UTF-8): specs,
// params, observed state, schemas. A JSON number stays a number that way,
// which a google.protobuf.Struct would turn into a double.
//
// Four rules a plugin must keep (ARCHITECTURE.md, "The plugin contract"):
//
//  1. Create, Delete and Act are IDEMPOTENT on the resource id. The core may
//     call them again after a crash, with the same resource and the same
//     params, and must get the same outcome — the plugin finds the engine
//     object it already made (by the id it wrote on it) instead of making a
//     second one. Delete of something already gone succeeds.
//  2. Plan has no side effects. The core calls it to learn what a request
//     would hold before it admits the request.
//  3. An action's params are absolute ("memory 8"), never relative
//     ("memory +2"), so that rule 1 holds for actions too.
//  4. Refusals are gRPC statuses: INVALID_ARGUMENT for a request that can
//     never succeed as written, FAILED_PRECONDITION for one the engine refuses
//     in its present state, UNAVAILABLE when the engine cannot be reached (the
//     core retries). Anything else is a failure.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: hangar/plugin/v1/plugin.proto

package pluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DimensionKind int32

const (
	DimensionKind_DIMENSION_KIND_UNSPECIFIED DimensionKind = 0
	// An amount summed over the owner's resources: a count, vCPU, GB.
	DimensionKind_DIMENSION_KIND_QUANTITY DimensionKind = 1
	// A value picked from a set the tier allows: a kind, a class, an image.
	DimensionKind_DIMENSION_KIND_CHOICE DimensionKind = 2
)

// Enum value maps for DimensionKind.
var (
	DimensionKind_name = map[int32]string{
		0: "DIMENSION_KIND_UNSPECIFIED",
		1: "DIMENSION_KIND_QUANTITY",
		2: "DIMENSION_KIND_CHOICE",
	}
	DimensionKind_value = map[string]int32{
		"DIMENSION_KIND_UNSPECIFIED": 0,
		"DIMENSION_KIND_QUANTITY":    1,
		"DIMENSION_KIND_CHOICE":      2,
	}
)

func (x DimensionKind) Enum() *DimensionKind {
	p := new(DimensionKind)
	*p = x
	return p
}

func (x DimensionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DimensionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_hangar_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (DimensionKind) Type() protoreflect.EnumType {
	return &file_hangar_plugin_v1_plugin_proto_enumTypes[0]
}

func (x DimensionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DimensionKind.Descriptor instead.
func (DimensionKind) EnumDescriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type Drift int32

const (
	Drift_DRIFT_UNSPECIFIED Drift = 0
	// Actual matches desired.
	Drift_DRIFT_IN_SYNC Drift = 1
	// It did not, and the plugin put it back.
	Drift_DRIFT_REPAIRED Drift = 2
	// It does not, and the plugin will not repair it itself (it says why).
	Drift_DRIFT_DRIFTED Drift = 3
	// The engine no longer has it.
	Drift_DRIFT_MISSING Drift = 4
)

// Enum value maps for Drift.
var (
	Drift_name = map[int32]string{
		0: "DRIFT_UNSPECIFIED",
		1: "DRIFT_IN_SYNC",
		2: "DRIFT_REPAIRED",
		3: "DRIFT_DRIFTED",
		4: "DRIFT_MISSING",
	}
	Drift_value = map[string]int32{
		"DRIFT_UNSPECIFIED": 0,
		"DRIFT_IN_SYNC":     1,
		"DRIFT_REPAIRED":    2,
		"DRIFT_DRIFTED":     3,
		"DRIFT_MISSING":     4,
	}
)

func (x Drift) Enum() *Drift {
	p := new(Drift)
	*p = x
	return p
}

func (x Drift) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Drift) Descriptor() protoreflect.EnumDescriptor {
	return file_hangar_plugin_v1_plugin_proto_enumTypes[1].Descriptor()
}

func (Drift) Type() protoreflect.EnumType {
	return &file_hangar_plugin_v1_plugin_proto_enumTypes[1]
}

func (x Drift) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Drift.Descriptor instead.
func (Drift) EnumDescriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

type DescribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The protocol the core speaks; a plugin that cannot speak it says so.
	Protocol      uint32 `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *DescribeRequest) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

type DescribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The plugin's own name. The operator's config enables it under this name,
	// and every dimension it declares is spelled "<name>.<something>".
	Name       string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version    string          `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Types      []*ResourceType `protobuf:"bytes,3,rep,name=types,proto3" json:"types,omitempty"`
	Dimensions []*Dimension    `protobuf:"bytes,4,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	// Capability flags every zone must have for the plugin to be enabled there.
	Requires []string `protobuf:"bytes,5,rep,name=requires,proto3" json:"requires,omitempty"`
	// The one secret it needs per zone. A description only: the value arrives
	// in Configure, and only this plugin's.
	Credential *Credential `protobuf:"bytes,6,opt,name=credential,proto3" json:"credential,omitempty"`
	// The names of the events it may emit (written to the audit).
	Events        []string `protobuf:"bytes,7,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DescribeResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DescribeResponse) GetTypes() []*ResourceType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *DescribeResponse) GetDimensions() []*Dimension {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *DescribeResponse) GetRequires() []string {
	if x != nil {
		return x.Requires
	}
	return nil
}

func (x *DescribeResponse) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *DescribeResponse) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

type ResourceType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "machine". Unique across every plugin a core runs.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// "m": the ids of this type read m-0123456789abcdef0. Unique across plugins.
	IdPrefix    string `protobuf:"bytes,2,opt,name=id_prefix,json=idPrefix,proto3" json:"id_prefix,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// A JSON Schema (draft 2020-12) of the spec. The core validates every
	// request against it before the plugin sees one, and the command line and
	// the console draw their flags and forms from it.
	Schema []byte `protobuf:"bytes,5,opt,name=schema,proto3" json:"schema,omitempty"`
	// Beyond create and delete, which every type has.
	Actions []*Action `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions,omitempty"`
	// Capability flags this type needs on a zone (on top of the plugin's).
	Requires      []string `protobuf:"bytes,7,rep,name=requires,proto3" json:"requires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceType) Reset() {
	*x = ResourceType{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceType) ProtoMessage() {}

func (x *ResourceType) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceType.ProtoReflect.Descriptor instead.
func (*ResourceType) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceType) GetIdPrefix() string {
	if x != nil {
		return x.IdPrefix
	}
	return ""
}

func (x *ResourceType) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ResourceType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResourceType) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *ResourceType) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ResourceType) GetRequires() []string {
	if x != nil {
		return x.Requires
	}
	return nil
}

type Action struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// A JSON Schema of its params; empty = it takes none.
	ParamsSchema []byte `protobuf:"bytes,3,opt,name=params_schema,json=paramsSchema,proto3" json:"params_schema,omitempty"`
	// true = it can change what the resource holds (a resize) or the room it
	// takes (a start, a stop): the core calls Plan first and admits the
	// difference against the owner's limits and the zone's pools.
	ChangesUsage bool `protobuf:"varint,4,opt,name=changes_usage,json=changesUsage,proto3" json:"changes_usage,omitempty"`
	// Capability flags it needs on the zone; where they are missing the action
	// is not offered there.
	Requires      []string `protobuf:"bytes,5,rep,name=requires,proto3" json:"requires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Action) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Action) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Action) GetParamsSchema() []byte {
	if x != nil {
		return x.ParamsSchema
	}
	return nil
}

func (x *Action) GetChangesUsage() bool {
	if x != nil {
		return x.ChangesUsage
	}
	return false
}

func (x *Action) GetRequires() []string {
	if x != nil {
		return x.Requires
	}
	return nil
}

type Dimension struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "<plugin>.<name>", e.g. "machines.memory_gb".
	Name string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind DimensionKind `protobuf:"varint,2,opt,name=kind,proto3,enum=hangar.plugin.v1.DimensionKind" json:"kind,omitempty"`
	// "GB", "vCPU"; empty for a count or a choice.
	Unit          string `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Description   string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dimension) Reset() {
	*x = Dimension{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dimension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dimension) ProtoMessage() {}

func (x *Dimension) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dimension.ProtoReflect.Descriptor instead.
func (*Dimension) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *Dimension) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dimension) GetKind() DimensionKind {
	if x != nil {
		return x.Kind
	}
	return DimensionKind_DIMENSION_KIND_UNSPECIFIED
}

func (x *Dimension) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Dimension) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Credential struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Required bool                   `protobuf:"varint,1,opt,name=required,proto3" json:"required,omitempty"`
	// What it is and the least it must be allowed to do, for the operator.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credential) Reset() {
	*x = Credential{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credential.ProtoReflect.Descriptor instead.
func (*Credential) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *Credential) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Credential) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Zones []*ZoneConfig          `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	// The plugin's own settings from the operator's config (JSON object).
	Settings      []byte `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigureRequest) GetZones() []*ZoneConfig {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *ConfigureRequest) GetSettings() []byte {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ZoneConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The engine driver's name ("fake", "proxmox", …) and how to reach it.
	Driver   string            `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	Endpoint string            `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Options  map[string]string `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// THIS plugin's credential for THIS zone. Never another plugin's.
	Credential []byte `protobuf:"bytes,5,opt,name=credential,proto3" json:"credential,omitempty"`
	// Guests outside the plugin's fence that the zone's reservations name
	// ("while guest X runs"): the driver may read their power, and nothing
	// more. The engine's own names for them.
	Watch         []string `protobuf:"bytes,6,rep,name=watch,proto3" json:"watch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneConfig) Reset() {
	*x = ZoneConfig{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneConfig) ProtoMessage() {}

func (x *ZoneConfig) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneConfig.ProtoReflect.Descriptor instead.
func (*ZoneConfig) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ZoneConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ZoneConfig) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *ZoneConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ZoneConfig) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ZoneConfig) GetCredential() []byte {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *ZoneConfig) GetWatch() []string {
	if x != nil {
		return x.Watch
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zones         []*ZoneReport          `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigureResponse) GetZones() []*ZoneReport {
	if x != nil {
		return x.Zones
	}
	return nil
}

type ZoneReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// What the driver it opened for this zone can do (capability flags).
	Capabilities []string `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Why the zone could not be opened; the core disables the plugin there.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneReport) Reset() {
	*x = ZoneReport{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneReport) ProtoMessage() {}

func (x *ZoneReport) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneReport.ProtoReflect.Descriptor instead.
func (*ZoneReport) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ZoneReport) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ZoneReport) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ZoneReport) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Zone  string                 `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	// The owner's subject, as the identity provider names them.
	Owner string `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	// Desired (JSON).
	Spec []byte `protobuf:"bytes,5,opt,name=spec,proto3" json:"spec,omitempty"`
	// Last observed (JSON), as the plugin last reported it.
	Observed []byte            `protobuf:"bytes,6,opt,name=observed,proto3" json:"observed,omitempty"`
	Tags     map[string]string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The hold the core places on the resource's borrowed room: "" = none;
	// otherwise the key of the reservation that needs the room now (letters,
	// digits, "-" and "_"). A plugin brings the engine to the held state in
	// Create, Act and Reconcile — what that means is the plugin's (a machine
	// borrowing all its memory stops; one with a floor shrinks to it) — and
	// back when the hold is lifted.
	Hold          string `protobuf:"bytes,8,opt,name=hold,proto3" json:"hold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Resource) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Resource) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Resource) GetObserved() []byte {
	if x != nil {
		return x.Observed
	}
	return nil
}

func (x *Resource) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Resource) GetHold() string {
	if x != nil {
		return x.Hold
	}
	return ""
}

type PlanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Zone  string                 `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	// Empty for a create; otherwise the action's name.
	Action string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	// A create's spec, already valid against the type's schema.
	Spec []byte `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// An action's params, already valid against its params schema.
	Params []byte `protobuf:"bytes,5,opt,name=params,proto3" json:"params,omitempty"`
	// For an action: the resource as the registry holds it.
	Current       *Resource `protobuf:"bytes,6,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanRequest) Reset() {
	*x = PlanRequest{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRequest) ProtoMessage() {}

func (x *PlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRequest.ProtoReflect.Descriptor instead.
func (*PlanRequest) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *PlanRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PlanRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *PlanRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PlanRequest) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *PlanRequest) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *PlanRequest) GetCurrent() *Resource {
	if x != nil {
		return x.Current
	}
	return nil
}

type PlanResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The desired spec once the request is done, defaults applied.
	Spec []byte `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	// Every QUANTITY dimension this resource would hold, whole (not a delta).
	Usage map[string]int64 `protobuf:"bytes,2,rep,name=usage,proto3" json:"usage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Every CHOICE dimension this resource would pick.
	Choices map[string]string `protobuf:"bytes,3,rep,name=choices,proto3" json:"choices,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Why the plugin refuses the request; empty = it does not.
	Refusals []*Refusal `protobuf:"bytes,4,rep,name=refusals,proto3" json:"refusals,omitempty"`
	// What the resource would take from its zone's room; absent = nothing
	// (a key pair, a record).
	Room          *Room `protobuf:"bytes,5,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanResponse) Reset() {
	*x = PlanResponse{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponse) ProtoMessage() {}

func (x *PlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponse.ProtoReflect.Descriptor instead.
func (*PlanResponse) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *PlanResponse) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *PlanResponse) GetUsage() map[string]int64 {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *PlanResponse) GetChoices() map[string]string {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *PlanResponse) GetRefusals() []*Refusal {
	if x != nil {
		return x.Refusals
	}
	return nil
}

func (x *PlanResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// Room is what a resource takes from its zone's memory, the way the zone's
// pools count it (ARCHITECTURE.md §6).
type Room struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MiB booked in the zone's guaranteed pool for as long as it exists.
	GuaranteedMb int64 `protobuf:"varint,1,opt,name=guaranteed_mb,json=guaranteedMb,proto3" json:"guaranteed_mb,omitempty"`
	// MiB borrowed from the zone's spot pool while it runs, given back when a
	// reservation needs the room.
	SpotMb int64 `protobuf:"varint,2,opt,name=spot_mb,json=spotMb,proto3" json:"spot_mb,omitempty"`
	// Whether it runs once the request is done (spot room is used only then).
	Running       bool `protobuf:"varint,3,opt,name=running,proto3" json:"running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *Room) GetGuaranteedMb() int64 {
	if x != nil {
		return x.GuaranteedMb
	}
	return 0
}

func (x *Room) GetSpotMb() int64 {
	if x != nil {
		return x.SpotMb
	}
	return 0
}

func (x *Room) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

type Refusal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A JSON pointer into the spec or params ("/memory_gb"); empty = the whole.
	Field         string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Refusal) Reset() {
	*x = Refusal{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Refusal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refusal) ProtoMessage() {}

func (x *Refusal) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refusal.ProtoReflect.Descriptor instead.
func (*Refusal) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *Refusal) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Refusal) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id is minted by the core before the call: write it on the engine
	// object, and find it again by it (rule 1).
	Resource *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// The resources the spec refers to — every field its schema marks with
	// "x-hangar-ref" — as the registry holds them. The core checked each is
	// the owner's own, in the same zone, and ready when it was asked for.
	Refs          []*Resource `protobuf:"bytes,2,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *CreateRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *CreateRequest) GetRefs() []*Resource {
	if x != nil {
		return x.Refs
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observed      []byte                 `protobuf:"bytes,1,opt,name=observed,proto3" json:"observed,omitempty"`
	Events        []*Event               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *CreateResponse) GetObserved() []byte {
	if x != nil {
		return x.Observed
	}
	return nil
}

func (x *CreateResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type ActRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Resource *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Action   string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Params   []byte                 `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	// The resources the params refer to ("x-hangar-ref"), checked as a
	// create's are.
	Refs          []*Resource `protobuf:"bytes,4,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActRequest) Reset() {
	*x = ActRequest{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActRequest) ProtoMessage() {}

func (x *ActRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActRequest.ProtoReflect.Descriptor instead.
func (*ActRequest) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *ActRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ActRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ActRequest) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ActRequest) GetRefs() []*Resource {
	if x != nil {
		return x.Refs
	}
	return nil
}

type ActResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The desired spec after the action (empty = unchanged).
	Spec     []byte `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Observed []byte `protobuf:"bytes,2,opt,name=observed,proto3" json:"observed,omitempty"`
	// What the action answers the person, if anything (JSON).
	Result        []byte   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Events        []*Event `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActResponse) Reset() {
	*x = ActResponse{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActResponse) ProtoMessage() {}

func (x *ActResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActResponse.ProtoReflect.Descriptor instead.
func (*ActResponse) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *ActResponse) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ActResponse) GetObserved() []byte {
	if x != nil {
		return x.Observed
	}
	return nil
}

func (x *ActResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ActResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type ReconcileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileRequest) Reset() {
	*x = ReconcileRequest{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileRequest) ProtoMessage() {}

func (x *ReconcileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileRequest.ProtoReflect.Descriptor instead.
func (*ReconcileRequest) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *ReconcileRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ReconcileResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Drift    Drift                  `protobuf:"varint,1,opt,name=drift,proto3,enum=hangar.plugin.v1.Drift" json:"drift,omitempty"`
	Detail   string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Observed []byte                 `protobuf:"bytes,3,opt,name=observed,proto3" json:"observed,omitempty"`
	Events   []*Event               `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	// The desired spec, when the plugin moved it — a machine a hold stopped
	// for good is no longer meant to run — with the room it now takes. Empty =
	// unchanged.
	Spec          []byte `protobuf:"bytes,5,opt,name=spec,proto3" json:"spec,omitempty"`
	Room          *Room  `protobuf:"bytes,6,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileResponse) Reset() {
	*x = ReconcileResponse{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileResponse) ProtoMessage() {}

func (x *ReconcileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileResponse.ProtoReflect.Descriptor instead.
func (*ReconcileResponse) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *ReconcileResponse) GetDrift() Drift {
	if x != nil {
		return x.Drift
	}
	return Drift_DRIFT_UNSPECIFIED
}

func (x *ReconcileResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ReconcileResponse) GetObserved() []byte {
	if x != nil {
		return x.Observed
	}
	return nil
}

func (x *ReconcileResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ReconcileResponse) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ReconcileResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type SurveyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Zone  string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	// The conditions the zone's reservations wait on.
	Conditions    []*Condition `protobuf:"bytes,2,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurveyRequest) Reset() {
	*x = SurveyRequest{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurveyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurveyRequest) ProtoMessage() {}

func (x *SurveyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurveyRequest.ProtoReflect.Descriptor instead.
func (*SurveyRequest) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *SurveyRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *SurveyRequest) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to What:
	//
	//	*Condition_GuestRunning
	//	*Condition_NodeDown
	What          isCondition_What `protobuf_oneof:"what"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *Condition) GetWhat() isCondition_What {
	if x != nil {
		return x.What
	}
	return nil
}

func (x *Condition) GetGuestRunning() string {
	if x != nil {
		if x, ok := x.What.(*Condition_GuestRunning); ok {
			return x.GuestRunning
		}
	}
	return ""
}

func (x *Condition) GetNodeDown() string {
	if x != nil {
		if x, ok := x.What.(*Condition_NodeDown); ok {
			return x.NodeDown
		}
	}
	return ""
}

type isCondition_What interface {
	isCondition_What()
}

type Condition_GuestRunning struct {
	// A guest, by the engine's own name (one of the zone's watch list), runs.
	GuestRunning string `protobuf:"bytes,1,opt,name=guest_running,json=guestRunning,proto3,oneof"`
}

type Condition_NodeDown struct {
	// A node of the engine is down.
	NodeDown string `protobuf:"bytes,2,opt,name=node_down,json=nodeDown,proto3,oneof"`
}

func (*Condition_GuestRunning) isCondition_What() {}

func (*Condition_NodeDown) isCondition_What() {}

type SurveyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One per condition asked, in the same order.
	Conditions []*ConditionState `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	// The plugin's resources whose engine objects carry a hold, by id: the key
	// written on them (by the core through the plugin, or by the engine's own
	// node acting alone when the core could not be reached).
	Holds map[string]string `protobuf:"bytes,2,rep,name=holds,proto3" json:"holds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Whether the zone's engine answers and its node is up (a zone that sleeps
	// is not awake).
	Awake         bool `protobuf:"varint,3,opt,name=awake,proto3" json:"awake,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurveyResponse) Reset() {
	*x = SurveyResponse{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurveyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurveyResponse) ProtoMessage() {}

func (x *SurveyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurveyResponse.ProtoReflect.Descriptor instead.
func (*SurveyResponse) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *SurveyResponse) GetConditions() []*ConditionState {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *SurveyResponse) GetHolds() map[string]string {
	if x != nil {
		return x.Holds
	}
	return nil
}

func (x *SurveyResponse) GetAwake() bool {
	if x != nil {
		return x.Awake
	}
	return false
}

type ConditionState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Met   bool                   `protobuf:"varint,1,opt,name=met,proto3" json:"met,omitempty"`
	// Why it could not be read; met is then false and the core keeps what it
	// knew.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionState) Reset() {
	*x = ConditionState{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionState) ProtoMessage() {}

func (x *ConditionState) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionState.ProtoReflect.Descriptor instead.
func (*ConditionState) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *ConditionState) GetMet() bool {
	if x != nil {
		return x.Met
	}
	return false
}

func (x *ConditionState) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One of the names the plugin declared in Describe.
	Name          string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message       string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_hangar_plugin_v1_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_hangar_plugin_v1_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_hangar_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_hangar_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1dhangar/plugin/v1/plugin.proto\x12\x10hangar.plugin.v1\"-\n" +
	"\x0fDescribeRequest\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\rR\bprotocol\"\xa5\x02\n" +
	"\x10DescribeResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x124\n" +
	"\x05types\x18\x03 \x03(\v2\x1e.hangar.plugin.v1.ResourceTypeR\x05types\x12;\n" +
	"\n" +
	"dimensions\x18\x04 \x03(\v2\x1b.hangar.plugin.v1.DimensionR\n" +
	"dimensions\x12\x1a\n" +
	"\brequires\x18\x05 \x03(\tR\brequires\x12<\n" +
	"\n" +
	"credential\x18\x06 \x01(\v2\x1c.hangar.plugin.v1.CredentialR\n" +
	"credential\x12\x16\n" +
	"\x06events\x18\a \x03(\tR\x06events\"\xdf\x01\n" +
	"\fResourceType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tid_prefix\x18\x02 \x01(\tR\bidPrefix\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06schema\x18\x05 \x01(\fR\x06schema\x122\n" +
	"\aactions\x18\x06 \x03(\v2\x18.hangar.plugin.v1.ActionR\aactions\x12\x1a\n" +
	"\brequires\x18\a \x03(\tR\brequires\"\xa4\x01\n" +
	"\x06Action\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12#\n" +
	"\rparams_schema\x18\x03 \x01(\fR\fparamsSchema\x12#\n" +
	"\rchanges_usage\x18\x04 \x01(\bR\fchangesUsage\x12\x1a\n" +
	"\brequires\x18\x05 \x03(\tR\brequires\"\x8a\x01\n" +
	"\tDimension\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1f.hangar.plugin.v1.DimensionKindR\x04kind\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"J\n" +
	"\n" +
	"Credential\x12\x1a\n" +
	"\brequired\x18\x01 \x01(\bR\brequired\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"b\n" +
	"\x10ConfigureRequest\x122\n" +
	"\x05zones\x18\x01 \x03(\v2\x1c.hangar.plugin.v1.ZoneConfigR\x05zones\x12\x1a\n" +
	"\bsettings\x18\x02 \x01(\fR\bsettings\"\x8b\x02\n" +
	"\n" +
	"ZoneConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12C\n" +
	"\aoptions\x18\x04 \x03(\v2).hangar.plugin.v1.ZoneConfig.OptionsEntryR\aoptions\x12\x1e\n" +
	"\n" +
	"credential\x18\x05 \x01(\fR\n" +
	"credential\x12\x14\n" +
	"\x05watch\x18\x06 \x03(\tR\x05watch\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x11ConfigureResponse\x122\n" +
	"\x05zones\x18\x01 \x03(\v2\x1c.hangar.plugin.v1.ZoneReportR\x05zones\"Z\n" +
	"\n" +
	"ZoneReport\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x8f\x02\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\tR\x04zone\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x12\n" +
	"\x04spec\x18\x05 \x01(\fR\x04spec\x12\x1a\n" +
	"\bobserved\x18\x06 \x01(\fR\bobserved\x128\n" +
	"\x04tags\x18\a \x03(\v2$.hangar.plugin.v1.Resource.TagsEntryR\x04tags\x12\x12\n" +
	"\x04hold\x18\b \x01(\tR\x04hold\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x01\n" +
	"\vPlanRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04zone\x18\x02 \x01(\tR\x04zone\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x12\n" +
	"\x04spec\x18\x04 \x01(\fR\x04spec\x12\x16\n" +
	"\x06params\x18\x05 \x01(\fR\x06params\x124\n" +
	"\acurrent\x18\x06 \x01(\v2\x1a.hangar.plugin.v1.ResourceR\acurrent\"\x83\x03\n" +
	"\fPlanResponse\x12\x12\n" +
	"\x04spec\x18\x01 \x01(\fR\x04spec\x12?\n" +
	"\x05usage\x18\x02 \x03(\v2).hangar.plugin.v1.PlanResponse.UsageEntryR\x05usage\x12E\n" +
	"\achoices\x18\x03 \x03(\v2+.hangar.plugin.v1.PlanResponse.ChoicesEntryR\achoices\x125\n" +
	"\brefusals\x18\x04 \x03(\v2\x19.hangar.plugin.v1.RefusalR\brefusals\x12*\n" +
	"\x04room\x18\x05 \x01(\v2\x16.hangar.plugin.v1.RoomR\x04room\x1a8\n" +
	"\n" +
	"UsageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a:\n" +
	"\fChoicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\x04Room\x12#\n" +
	"\rguaranteed_mb\x18\x01 \x01(\x03R\fguaranteedMb\x12\x17\n" +
	"\aspot_mb\x18\x02 \x01(\x03R\x06spotMb\x12\x18\n" +
	"\arunning\x18\x03 \x01(\bR\arunning\"7\n" +
	"\aRefusal\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"w\n" +
	"\rCreateRequest\x126\n" +
	"\bresource\x18\x01 \x01(\v2\x1a.hangar.plugin.v1.ResourceR\bresource\x12.\n" +
	"\x04refs\x18\x02 \x03(\v2\x1a.hangar.plugin.v1.ResourceR\x04refs\"]\n" +
	"\x0eCreateResponse\x12\x1a\n" +
	"\bobserved\x18\x01 \x01(\fR\bobserved\x12/\n" +
	"\x06events\x18\x02 \x03(\v2\x17.hangar.plugin.v1.EventR\x06events\"G\n" +
	"\rDeleteRequest\x126\n" +
	"\bresource\x18\x01 \x01(\v2\x1a.hangar.plugin.v1.ResourceR\bresource\"A\n" +
	"\x0eDeleteResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.hangar.plugin.v1.EventR\x06events\"\xa4\x01\n" +
	"\n" +
	"ActRequest\x126\n" +
	"\bresource\x18\x01 \x01(\v2\x1a.hangar.plugin.v1.ResourceR\bresource\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x16\n" +
	"\x06params\x18\x03 \x01(\fR\x06params\x12.\n" +
	"\x04refs\x18\x04 \x03(\v2\x1a.hangar.plugin.v1.ResourceR\x04refs\"\x86\x01\n" +
	"\vActResponse\x12\x12\n" +
	"\x04spec\x18\x01 \x01(\fR\x04spec\x12\x1a\n" +
	"\bobserved\x18\x02 \x01(\fR\bobserved\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\x12/\n" +
	"\x06events\x18\x04 \x03(\v2\x17.hangar.plugin.v1.EventR\x06events\"J\n" +
	"\x10ReconcileRequest\x126\n" +
	"\bresource\x18\x01 \x01(\v2\x1a.hangar.plugin.v1.ResourceR\bresource\"\xe7\x01\n" +
	"\x11ReconcileResponse\x12-\n" +
	"\x05drift\x18\x01 \x01(\x0e2\x17.hangar.plugin.v1.DriftR\x05drift\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12\x1a\n" +
	"\bobserved\x18\x03 \x01(\fR\bobserved\x12/\n" +
	"\x06events\x18\x04 \x03(\v2\x17.hangar.plugin.v1.EventR\x06events\x12\x12\n" +
	"\x04spec\x18\x05 \x01(\fR\x04spec\x12*\n" +
	"\x04room\x18\x06 \x01(\v2\x16.hangar.plugin.v1.RoomR\x04room\"`\n" +
	"\rSurveyRequest\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\x12;\n" +
	"\n" +
	"conditions\x18\x02 \x03(\v2\x1b.hangar.plugin.v1.ConditionR\n" +
	"conditions\"Y\n" +
	"\tCondition\x12%\n" +
	"\rguest_running\x18\x01 \x01(\tH\x00R\fguestRunning\x12\x1d\n" +
	"\tnode_down\x18\x02 \x01(\tH\x00R\bnodeDownB\x06\n" +
	"\x04what\"\xe5\x01\n" +
	"\x0eSurveyResponse\x12@\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2 .hangar.plugin.v1.ConditionStateR\n" +
	"conditions\x12A\n" +
	"\x05holds\x18\x02 \x03(\v2+.hangar.plugin.v1.SurveyResponse.HoldsEntryR\x05holds\x12\x14\n" +
	"\x05awake\x18\x03 \x01(\bR\x05awake\x1a8\n" +
	"\n" +
	"HoldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\x0eConditionState\x12\x10\n" +
	"\x03met\x18\x01 \x01(\bR\x03met\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xad\x01\n" +
	"\x05Event\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\x06fields\x18\x03 \x03(\v2#.hangar.plugin.v1.Event.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*g\n" +
	"\rDimensionKind\x12\x1e\n" +
	"\x1aDIMENSION_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DIMENSION_KIND_QUANTITY\x10\x01\x12\x19\n" +
	"\x15DIMENSION_KIND_CHOICE\x10\x02*k\n" +
	"\x05Drift\x12\x15\n" +
	"\x11DRIFT_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rDRIFT_IN_SYNC\x10\x01\x12\x12\n" +
	"\x0eDRIFT_REPAIRED\x10\x02\x12\x11\n" +
	"\rDRIFT_DRIFTED\x10\x03\x12\x11\n" +
	"\rDRIFT_MISSING\x10\x042\x80\x05\n" +
	"\rPluginService\x12Q\n" +
	"\bDescribe\x12!.hangar.plugin.v1.DescribeRequest\x1a\".hangar.plugin.v1.DescribeResponse\x12T\n" +
	"\tConfigure\x12\".hangar.plugin.v1.ConfigureRequest\x1a#.hangar.plugin.v1.ConfigureResponse\x12E\n" +
	"\x04Plan\x12\x1d.hangar.plugin.v1.PlanRequest\x1a\x1e.hangar.plugin.v1.PlanResponse\x12K\n" +
	"\x06Create\x12\x1f.hangar.plugin.v1.CreateRequest\x1a .hangar.plugin.v1.CreateResponse\x12K\n" +
	"\x06Delete\x12\x1f.hangar.plugin.v1.DeleteRequest\x1a .hangar.plugin.v1.DeleteResponse\x12B\n" +
	"\x03Act\x12\x1c.hangar.plugin.v1.ActRequest\x1a\x1d.hangar.plugin.v1.ActResponse\x12T\n" +
	"\tReconcile\x12\".hangar.plugin.v1.ReconcileRequest\x1a#.hangar.plugin.v1.ReconcileResponse\x12K\n" +
	"\x06Survey\x12\x1f.hangar.plugin.v1.SurveyRequest\x1a .hangar.plugin.v1.SurveyResponseB,Z*github.com/tomblancdev/hangar/sdk/pluginpbb\x06proto3"

var (
	file_hangar_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_hangar_plugin_v1_plugin_proto_rawDescData []byte
)

func file_hangar_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_hangar_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_hangar_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hangar_plugin_v1_plugin_proto_rawDesc), len(file_hangar_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_hangar_plugin_v1_plugin_proto_rawDescData
}

var file_hangar_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_hangar_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_hangar_plugin_v1_plugin_proto_goTypes = []any{
	(DimensionKind)(0),        // 0: hangar.plugin.v1.DimensionKind
	(Drift)(0),                // 1: hangar.plugin.v1.Drift
	(*DescribeRequest)(nil),   // 2: hangar.plugin.v1.DescribeRequest
	(*DescribeResponse)(nil),  // 3: hangar.plugin.v1.DescribeResponse
	(*ResourceType)(nil),      // 4: hangar.plugin.v1.ResourceType
	(*Action)(nil),            // 5: hangar.plugin.v1.Action
	(*Dimension)(nil),         // 6: hangar.plugin.v1.Dimension
	(*Credential)(nil),        // 7: hangar.plugin.v1.Credential
	(*ConfigureRequest)(nil),  // 8: hangar.plugin.v1.ConfigureRequest
	(*ZoneConfig)(nil),        // 9: hangar.plugin.v1.ZoneConfig
	(*ConfigureResponse)(nil), // 10: hangar.plugin.v1.ConfigureResponse
	(*ZoneReport)(nil),        // 11: hangar.plugin.v1.ZoneReport
	(*Resource)(nil),          // 12: hangar.plugin.v1.Resource
	(*PlanRequest)(nil),       // 13: hangar.plugin.v1.PlanRequest
	(*PlanResponse)(nil),      // 14: hangar.plugin.v1.PlanResponse
	(*Room)(nil),              // 15: hangar.plugin.v1.Room
	(*Refusal)(nil),           // 16: hangar.plugin.v1.Refusal
	(*CreateRequest)(nil),     // 17: hangar.plugin.v1.CreateRequest
	(*CreateResponse)(nil),    // 18: hangar.plugin.v1.CreateResponse
	(*DeleteRequest)(nil),     // 19: hangar.plugin.v1.DeleteRequest
	(*DeleteResponse)(nil),    // 20: hangar.plugin.v1.DeleteResponse
	(*ActRequest)(nil),        // 21: hangar.plugin.v1.ActRequest
	(*ActResponse)(nil),       // 22: hangar.plugin.v1.ActResponse
	(*ReconcileRequest)(nil),  // 23: hangar.plugin.v1.ReconcileRequest
	(*ReconcileResponse)(nil), // 24: hangar.plugin.v1.ReconcileResponse
	(*SurveyRequest)(nil),     // 25: hangar.plugin.v1.SurveyRequest
	(*Condition)(nil),         // 26: hangar.plugin.v1.Condition
	(*SurveyResponse)(nil),    // 27: hangar.plugin.v1.SurveyResponse
	(*ConditionState)(nil),    // 28: hangar.plugin.v1.ConditionState
	(*Event)(nil),             // 29: hangar.plugin.v1.Event
	nil,                       // 30: hangar.plugin.v1.ZoneConfig.OptionsEntry
	nil,                       // 31: hangar.plugin.v1.Resource.TagsEntry
	nil,                       // 32: hangar.plugin.v1.PlanResponse.UsageEntry
	nil,                       // 33: hangar.plugin.v1.PlanResponse.ChoicesEntry
	nil,                       // 34: hangar.plugin.v1.SurveyResponse.HoldsEntry
	nil,                       // 35: hangar.plugin.v1.Event.FieldsEntry
}
var file_hangar_plugin_v1_plugin_proto_depIdxs = []int32{
	4,  // 0: hangar.plugin.v1.DescribeResponse.types:type_name -> hangar.plugin.v1.ResourceType
	6,  // 1: hangar.plugin.v1.DescribeResponse.dimensions:type_name -> hangar.plugin.v1.Dimension
	7,  // 2: hangar.plugin.v1.DescribeResponse.credential:type_name -> hangar.plugin.v1.Credential
	5,  // 3: hangar.plugin.v1.ResourceType.actions:type_name -> hangar.plugin.v1.Action
	0,  // 4: hangar.plugin.v1.Dimension.kind:type_name -> hangar.plugin.v1.DimensionKind
	9,  // 5: hangar.plugin.v1.ConfigureRequest.zones:type_name -> hangar.plugin.v1.ZoneConfig
	30, // 6: hangar.plugin.v1.ZoneConfig.options:type_name -> hangar.plugin.v1.ZoneConfig.OptionsEntry
	11, // 7: hangar.plugin.v1.ConfigureResponse.zones:type_name -> hangar.plugin.v1.ZoneReport
	31, // 8: hangar.plugin.v1.Resource.tags:type_name -> hangar.plugin.v1.Resource.TagsEntry
	12, // 9: hangar.plugin.v1.PlanRequest.current:type_name -> hangar.plugin.v1.Resource
	32, // 10: hangar.plugin.v1.PlanResponse.usage:type_name -> hangar.plugin.v1.PlanResponse.UsageEntry
	33, // 11: hangar.plugin.v1.PlanResponse.choices:type_name -> hangar.plugin.v1.PlanResponse.ChoicesEntry
	16, // 12: hangar.plugin.v1.PlanResponse.refusals:type_name -> hangar.plugin.v1.Refusal
	15, // 13: hangar.plugin.v1.PlanResponse.room:type_name -> hangar.plugin.v1.Room
	12, // 14: hangar.plugin.v1.CreateRequest.resource:type_name -> hangar.plugin.v1.Resource
	12, // 15: hangar.plugin.v1.CreateRequest.refs:type_name -> hangar.plugin.v1.Resource
	29, // 16: hangar.plugin.v1.CreateResponse.events:type_name -> hangar.plugin.v1.Event
	12, // 17: hangar.plugin.v1.DeleteRequest.resource:type_name -> hangar.plugin.v1.Resource
	29, // 18: hangar.plugin.v1.DeleteResponse.events:type_name -> hangar.plugin.v1.Event
	12, // 19: hangar.plugin.v1.ActRequest.resource:type_name -> hangar.plugin.v1.Resource
	12, // 20: hangar.plugin.v1.ActRequest.refs:type_name -> hangar.plugin.v1.Resource
	29, // 21: hangar.plugin.v1.ActResponse.events:type_name -> hangar.plugin.v1.Event
	12, // 22: hangar.plugin.v1.ReconcileRequest.resource:type_name -> hangar.plugin.v1.Resource
	1,  // 23: hangar.plugin.v1.ReconcileResponse.drift:type_name -> hangar.plugin.v1.Drift
	29, // 24: hangar.plugin.v1.ReconcileResponse.events:type_name -> hangar.plugin.v1.Event
	15, // 25: hangar.plugin.v1.ReconcileResponse.room:type_name -> hangar.plugin.v1.Room
	26, // 26: hangar.plugin.v1.SurveyRequest.conditions:type_name -> hangar.plugin.v1.Condition
	28, // 27: hangar.plugin.v1.SurveyResponse.conditions:type_name -> hangar.plugin.v1.ConditionState
	34, // 28: hangar.plugin.v1.SurveyResponse.holds:type_name -> hangar.plugin.v1.SurveyResponse.HoldsEntry
	35, // 29: hangar.plugin.v1.Event.fields:type_name -> hangar.plugin.v1.Event.FieldsEntry
	2,  // 30: hangar.plugin.v1.PluginService.Describe:input_type -> hangar.plugin.v1.DescribeRequest
	8,  // 31: hangar.plugin.v1.PluginService.Configure:input_type -> hangar.plugin.v1.ConfigureRequest
	13, // 32: hangar.plugin.v1.PluginService.Plan:input_type -> hangar.plugin.v1.PlanRequest
	17, // 33: hangar.plugin.v1.PluginService.Create:input_type -> hangar.plugin.v1.CreateRequest
	19, // 34: hangar.plugin.v1.PluginService.Delete:input_type -> hangar.plugin.v1.DeleteRequest
	21, // 35: hangar.plugin.v1.PluginService.Act:input_type -> hangar.plugin.v1.ActRequest
	23, // 36: hangar.plugin.v1.PluginService.Reconcile:input_type -> hangar.plugin.v1.ReconcileRequest
	25, // 37: hangar.plugin.v1.PluginService.Survey:input_type -> hangar.plugin.v1.SurveyRequest
	3,  // 38: hangar.plugin.v1.PluginService.Describe:output_type -> hangar.plugin.v1.DescribeResponse
	10, // 39: hangar.plugin.v1.PluginService.Configure:output_type -> hangar.plugin.v1.ConfigureResponse
	14, // 40: hangar.plugin.v1.PluginService.Plan:output_type -> hangar.plugin.v1.PlanResponse
	18, // 41: hangar.plugin.v1.PluginService.Create:output_type -> hangar.plugin.v1.CreateResponse
	20, // 42: hangar.plugin.v1.PluginService.Delete:output_type -> hangar.plugin.v1.DeleteResponse
	22, // 43: hangar.plugin.v1.PluginService.Act:output_type -> hangar.plugin.v1.ActResponse
	24, // 44: hangar.plugin.v1.PluginService.Reconcile:output_type -> hangar.plugin.v1.ReconcileResponse
	27, // 45: hangar.plugin.v1.PluginService.Survey:output_type -> hangar.plugin.v1.SurveyResponse
	38, // [38:46] is the sub-list for method output_type
	30, // [30:38] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_hangar_plugin_v1_plugin_proto_init() }
func file_hangar_plugin_v1_plugin_proto_init() {
	if File_hangar_plugin_v1_plugin_proto != nil {
		return
	}
	file_hangar_plugin_v1_plugin_proto_msgTypes[24].OneofWrappers = []any{
		(*Condition_GuestRunning)(nil),
		(*Condition_NodeDown)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hangar_plugin_v1_plugin_proto_rawDesc), len(file_hangar_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hangar_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_hangar_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_hangar_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_hangar_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_hangar_plugin_v1_plugin_proto = out.File
	file_hangar_plugin_v1_plugin_proto_goTypes = nil
	file_hangar_plugin_v1_plugin_proto_depIdxs = nil
}
