// The contract between the hangar core and a plugin.
//
// Everything a person can ask for is a plugin. A plugin DECLARES what it
// offers (Describe) and ACTS when the core asks it to (Configure, Plan,
// Create, Delete, Act, Reconcile). It never calls the core, it never sees
// another plugin's credential, and it never decides who may ask: identity,
// tiers, limits, the registry and the audit belong to the core.
//
// Values that are JSON documents travel as bytes holding JSON (UTF-8): specs,
// params, observed state, schemas. A JSON number stays a number that way,
// which a google.protobuf.Struct would turn into a double.
//
// Four rules a plugin must keep (ARCHITECTURE.md, "The plugin contract"):
//
//  1. Create, Delete and Act are IDEMPOTENT on the resource id. The core may
//     call them again after a crash, with the same resource and the same
//     params, and must get the same outcome — the plugin finds the engine
//     object it already made (by the id it wrote on it) instead of making a
//     second one. Delete of something already gone succeeds.
//  2. Plan has no side effects. The core calls it to learn what a request
//     would hold before it admits the request.
//  3. An action's params are absolute ("memory 8"), never relative
//     ("memory +2"), so that rule 1 holds for actions too.
//  4. Refusals are gRPC statuses: INVALID_ARGUMENT for a request that can
//     never succeed as written, FAILED_PRECONDITION for one the engine refuses
//     in its present state, UNAVAILABLE when the engine cannot be reached (the
//     core retries). Anything else is a failure.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: hangar/plugin/v1/plugin.proto

package pluginpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginService_Describe_FullMethodName   = "/hangar.plugin.v1.PluginService/Describe"
	PluginService_Configure_FullMethodName  = "/hangar.plugin.v1.PluginService/Configure"
	PluginService_Plan_FullMethodName       = "/hangar.plugin.v1.PluginService/Plan"
	PluginService_PlanChange_FullMethodName = "/hangar.plugin.v1.PluginService/PlanChange"
	PluginService_Create_FullMethodName     = "/hangar.plugin.v1.PluginService/Create"
	PluginService_Delete_FullMethodName     = "/hangar.plugin.v1.PluginService/Delete"
	PluginService_Act_FullMethodName        = "/hangar.plugin.v1.PluginService/Act"
	PluginService_Reconcile_FullMethodName  = "/hangar.plugin.v1.PluginService/Reconcile"
	PluginService_Survey_FullMethodName     = "/hangar.plugin.v1.PluginService/Survey"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginServiceClient interface {
	// What the plugin offers. Called once, before anything else.
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	// The zones the operator enabled it on, each with THIS plugin's credential
	// for that zone. The plugin opens its driver per zone and reports what the
	// driver can do.
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	// What a create or an action would hold, without doing it.
	Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error)
	// What it takes to bring a resource to another spec: the actions, in
	// order, or the fields no action changes (set at its birth). No side
	// effects. A plugin that leaves it unimplemented has types that change only
	// through their actions, asked one by one.
	PlanChange(ctx context.Context, in *PlanChangeRequest, opts ...grpc.CallOption) (*PlanChangeResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Act(ctx context.Context, in *ActRequest, opts ...grpc.CallOption) (*ActResponse, error)
	// Desired (the registry) against actual (the engine): repaired or reported.
	Reconcile(ctx context.Context, in *ReconcileRequest, opts ...grpc.CallOption) (*ReconcileResponse, error)
	// What the engine says about a zone's room now: whether the conditions its
	// reservations wait on are met, which of the plugin's resources carry a
	// hold the core may not have placed, and whether the zone is awake. A
	// plugin whose resources take no room leaves it unimplemented.
	Survey(ctx context.Context, in *SurveyRequest, opts ...grpc.CallOption) (*SurveyResponse, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, PluginService_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, PluginService_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanResponse)
	err := c.cc.Invoke(ctx, PluginService_Plan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) PlanChange(ctx context.Context, in *PlanChangeRequest, opts ...grpc.CallOption) (*PlanChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanChangeResponse)
	err := c.cc.Invoke(ctx, PluginService_PlanChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, PluginService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, PluginService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Act(ctx context.Context, in *ActRequest, opts ...grpc.CallOption) (*ActResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActResponse)
	err := c.cc.Invoke(ctx, PluginService_Act_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Reconcile(ctx context.Context, in *ReconcileRequest, opts ...grpc.CallOption) (*ReconcileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconcileResponse)
	err := c.cc.Invoke(ctx, PluginService_Reconcile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Survey(ctx context.Context, in *SurveyRequest, opts ...grpc.CallOption) (*SurveyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SurveyResponse)
	err := c.cc.Invoke(ctx, PluginService_Survey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility.
type PluginServiceServer interface {
	// What the plugin offers. Called once, before anything else.
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	// The zones the operator enabled it on, each with THIS plugin's credential
	// for that zone. The plugin opens its driver per zone and reports what the
	// driver can do.
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	// What a create or an action would hold, without doing it.
	Plan(context.Context, *PlanRequest) (*PlanResponse, error)
	// What it takes to bring a resource to another spec: the actions, in
	// order, or the fields no action changes (set at its birth). No side
	// effects. A plugin that leaves it unimplemented has types that change only
	// through their actions, asked one by one.
	PlanChange(context.Context, *PlanChangeRequest) (*PlanChangeResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Act(context.Context, *ActRequest) (*ActResponse, error)
	// Desired (the registry) against actual (the engine): repaired or reported.
	Reconcile(context.Context, *ReconcileRequest) (*ReconcileResponse, error)
	// What the engine says about a zone's room now: whether the conditions its
	// reservations wait on are met, which of the plugin's resources carry a
	// hold the core may not have placed, and whether the zone is awake. A
	// plugin whose resources take no room leaves it unimplemented.
	Survey(context.Context, *SurveyRequest) (*SurveyResponse, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServiceServer struct{}

func (UnimplementedPluginServiceServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedPluginServiceServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedPluginServiceServer) Plan(context.Context, *PlanRequest) (*PlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Plan not implemented")
}
func (UnimplementedPluginServiceServer) PlanChange(context.Context, *PlanChangeRequest) (*PlanChangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanChange not implemented")
}
func (UnimplementedPluginServiceServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPluginServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPluginServiceServer) Act(context.Context, *ActRequest) (*ActResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Act not implemented")
}
func (UnimplementedPluginServiceServer) Reconcile(context.Context, *ReconcileRequest) (*ReconcileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reconcile not implemented")
}
func (UnimplementedPluginServiceServer) Survey(context.Context, *SurveyRequest) (*SurveyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Survey not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}
func (UnimplementedPluginServiceServer) testEmbeddedByValue()                       {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Plan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Plan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Plan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Plan(ctx, req.(*PlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_PlanChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).PlanChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_PlanChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).PlanChange(ctx, req.(*PlanChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Act_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Act(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Act_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Act(ctx, req.(*ActRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Reconcile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Reconcile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Reconcile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Reconcile(ctx, req.(*ReconcileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Survey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Survey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Survey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Survey(ctx, req.(*SurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hangar.plugin.v1.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _PluginService_Describe_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _PluginService_Configure_Handler,
		},
		{
			MethodName: "Plan",
			Handler:    _PluginService_Plan_Handler,
		},
		{
			MethodName: "PlanChange",
			Handler:    _PluginService_PlanChange_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _PluginService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PluginService_Delete_Handler,
		},
		{
			MethodName: "Act",
			Handler:    _PluginService_Act_Handler,
		},
		{
			MethodName: "Reconcile",
			Handler:    _PluginService_Reconcile_Handler,
		},
		{
			MethodName: "Survey",
			Handler:    _PluginService_Survey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hangar/plugin/v1/plugin.proto",
}
