package ui

import (
	"bytes"
	"encoding/xml"
	"io"
	"strings"
	"testing"
)

// The substitution is a regex against an asset that gets regenerated by hand.
// If the two ever drift apart the replace silently does nothing and the mark
// keeps shipping whatever word is baked in — which is the whole bug this
// package exists to prevent. So: assert it actually replaced something.

func TestLockupShipsTheProductsName(t *testing.T) {
	got := string(Lockup(""))
	if !strings.Contains(got, tspans("LE HANGAR")) {
		t.Fatal("the shipped mark must spell LE HANGAR")
	}
	if !strings.Contains(got, `aria-label="le hangar`) {
		t.Fatalf("the shipped mark must name itself in its accessible name")
	}
}

func TestLockupSubstitutesTheOperatorsHouse(t *testing.T) {
	got := string(Lockup("Example House"))
	if !strings.Contains(got, tspans("EXAMPLE HOUSE")) {
		t.Fatal("a configured house word must appear in the wordmark")
	}
	if strings.Contains(got, tspans("LE HANGAR")) {
		t.Fatal("the product's own word must be gone once a house replaced it")
	}
	if !strings.Contains(got, `aria-label="Example House — le hangar"`) {
		t.Fatal("the accessible name must carry both the house and the product")
	}
	if bytes.Equal(Lockup("Example House"), Lockup("")) {
		t.Fatal("substitution did nothing: the regex no longer matches the asset")
	}
}

func TestLockupWithoutAHouseIsTheAssetItself(t *testing.T) {
	if !bytes.Equal(Lockup(""), Lockup("   ")) {
		t.Fatal("a blank house is no house")
	}
}

// The mark is shown as an image, and an image's SVG is XML: one stray "<" in
// it — a tag named in a comment of its stylesheet was enough — and no
// browser draws it, while nothing complains.
func TestTheMarkIsWellFormed(t *testing.T) {
	for _, house := range []string{"", "Example House", `A & B <"x">`} {
		dec := xml.NewDecoder(bytes.NewReader(Lockup(house)))
		for {
			if _, err := dec.Token(); err == io.EOF {
				break
			} else if err != nil {
				t.Fatalf("the mark for house %q is not well-formed XML: %v", house, err)
			}
		}
	}
}

func TestTheMarkAtRest(t *testing.T) {
	still := Still("Example House")
	if bytes.Equal(still, Lockup("Example House")) {
		t.Fatal("Still changed nothing: the asset no longer says how it looks without motion")
	}
	if !strings.Contains(string(still), tspans("EXAMPLE HOUSE")) {
		t.Fatal("the mark at rest lost the house word")
	}
	if err := xml.NewDecoder(bytes.NewReader(still)).Decode(new(struct{})); err != nil {
		t.Fatalf("the mark at rest is not well-formed XML: %v", err)
	}
}
